import { Car } from '@/types/interfaces';


export const cars: Car[] = [
  {
    id: 'idTeslaX20204/5YesReducer',
    mark: 'Tesla',
    model: 'X',
    year: 2020,
    doors: '4/5',
    ac: 'Yes',
    transmission: 'Reducer',
    fuel: 'Electricity',
    price: 295,
    img: 'tesla-model-x',
  },
  {
    id: 'idVolkswagenPolo20124/5YesManual',
    mark: 'Volkswagen',
    model: 'Polo',
    year: 2012,
    doors: '4/5',
    ac: 'Yes',
    transmission: 'Manual',
    fuel: 'Diesel',
    price: 75,
    img: 'volkswagen-polo',
  },
  {
    id: 'idFordMustang20152/3YesAuto',
    mark: 'Ford',
    model: 'Mustang',
    year: 2015,
    doors: '2/3',
    ac: 'Yes',
    transmission: 'Auto',
    fuel: 'Gasoline',
    price: 195,
    img: 'ford-mustang',
  },
  {
    id: 'idBMWX620184/5YesAuto',
    mark: 'BMW',
    model: 'X6',
    year: 2018,
    doors: '4/5',
    ac: 'Yes',
    transmission: 'Auto',
    fuel: 'Gasoline',
    price: 275,
    img: 'bmw-x6',
  },
  {
    id: 'idToyotaPrius20174/5YesAuto',
    mark: 'Toyota',
    model: 'Prius',
    year: 2017,
    doors: '4/5',
    ac: 'Yes',
    transmission: 'Auto',
    fuel: 'Hybrid',
    price: 85,
    img: 'toyota-prius',
  },
  {
    id: 'idMiniCooper20104/5YesManual',
    mark: 'Mini',
    model: 'Cooper',
    year: 2010,
    doors: '2/3',
    ac: 'Yes',
    transmission: 'Manual',
    fuel: 'Gasoline',
    price: 65,
    img: 'mini-cooper',
  },
  {
    id: 'idReanaultClio20214/5YesAuto',
    mark: 'Renault',
    model: 'Clio',
    year: 2021,
    doors: '4/5',
    ac: 'Yes',
    transmission: 'Auto',
    fuel: 'Gasoline',
    price: 85,
    img: 'renault-clio',
  }
]